name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push server Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./server-side
          file: ./server-side/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-project-server:latest

      - name: Build and push client Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./client-side
          file: ./client-side/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-project-client:latest

      - name: Build and push extension Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./extension-ui
          file: ./extension-ui/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-project-extension:latest
